### ISSUE TITLE
OF 0.9.0 compile errors

### ISSUE THREAD

**Issue by antimodular** [mrbichel/ofxVideoGrabberPvAPI#1]
Hi

Does your addon work in OF 0.9.0 on OS X 10.10

I have tried compile it but get a due to architecture problems. 
Just wondering if the PvAPI even works on 64bit?

Do you have an example that works?

Thanks a bunch.

**Comment by smukkejohan** [comment]
No I didn't work on this since 0.8.4. Changes should be quite simple though.

**Comment by antimodular** [comment]
thanks for getting back to me.
i tried a bunch of things, making changed to which c++ compile is being used, downloading the PVAPI libs from AVT, etc. 
nothing has worked so far. :(

**Comment by smukkejohan** [comment]
I'm not going to have time to look at it anytime soon. I don't have the camera at hand either. 
Maybe have a look at https://github.com/gaborpapp/Cinder-PvApi thats much more full fledged and recently updated and looks like they have 64 bit support.

**Comment by antimodular** [comment]
thanks for the hint. much appreciated.
